#  بسم_الله_الرحمن_الرحيم



# Numpy 

In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
arr =np.array([1,3,4,4])
print(arr)
type(arr)
print(type(arr))


[1 3 4 4]
<class 'numpy.ndarray'>


In [5]:
arr1 = np.array((1,3,4,3))
print(arr1)
type(arr1)

[1 3 4 3]


numpy.ndarray

## Dimensions in Array

# 0 d array

In [7]:
arr = np.array(5) # 1 hi element hai
print(arr)
print(arr.ndim , "dimension") # dimension 
print(type(arr))

arr2 = np.array([[5,4,3,2],[2,3,4,5]] , ndmin = 3)
print(arr2)
print(arr2.ndim)




5
0 dimension
<class 'numpy.ndarray'>
[[[5 4 3 2]
  [2 3 4 5]]]
3


## 1 d array

In [24]:
arr2 =  np.array([1,2,3,4])
print(arr2)
for i in arr2:
    print(i)
print("this array is" , arr2.ndim , "dimesnion")


[1 2 3 4]
1
2
3
4
this array is 1 dimesnion


## 2d

In [31]:
arr = np.array([[1,2,3,4],[23,3,3,7]])
print(arr)
print("the dimension is " , arr.ndim)

[[ 1  2  3  4]
 [23  3  3  7]]
the dimension is  2


In [38]:
arr_2d = np.array([[1,3,4,4],[2,3,4,3]])
print(arr_2d)
print("dimension",arr_2d.ndim)

[[1 3 4 4]
 [2 3 4 3]]
dimension 2


## 3d

In [8]:
arr = np.array([[1,3,4],
[1,3,4],
[1,4,2]] , ndmin=4)
print(arr)
print("dim",arr.ndim)

[[[[1 3 4]
   [1 3 4]
   [1 4 2]]]]
dim 4


In [9]:
print(arr.dtype)
print(arr.shape)
print(arr.size)

int64
(1, 1, 3, 3)
9


In [ ]:
l = [1,3,4,4]
print(mean(l))
    

NameError: name 'mean' is not defined

In [59]:
l = np.array([1,3,4,5])
print(np.mean(l))


3.25


## array by default values

In [10]:
print(np.eye(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
print(np.arange(1,10,2))
for i in range(1,10,2):
    print(i, end=" ")

[1 3 5 7 9]
1 3 5 7 9 

In [ ]:

print(np.zeros((3,3)))

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print(np.full((2,2),8))

[[8 8]
 [8 8]]


## dtype

In [ ]:
import numpy as np

arr = np.array([1, 3, 5.3])
print(arr.dtype)


TypeError: data type 's' not understood

In [14]:
h = np.array([1.3,3.4,2.4])
m = h.astype(int)
print(h)
print(m)

[1.3 3.4 2.4]
[1 3 2]


In [34]:
phone = np.array(["03347426966"])
new_ph = phone.astype(int)
print(phone)
print(new_ph)
print(phone.dtype)
print(new_ph.dtype)

['03347426966']
[3347426966]
<U11
int64


In [ ]:
array_3d = np.array([[[1,2,3],[1,2,4],[1,2,3]]])
print(array_3d)
print(array_3d.dtype)
print(array_3d.ndim)


[[[1 2 3]
  [1 2 4]
  [1 2 3]]]
int64
3


In [31]:
eishal = np.array([[[1,2,3]]])
print(eishal)
print(eishal.ndim)

[[[1 2 3]]]
3


In [13]:
a = np.array(90)
b = np.array([1,3,4])
c = np.array([[1,3,4],[1,3,4]])
d = np.array([[[1,2,3],[1,3,4],[13,4,2]]])
e = np.array([[[[1,2,3],[23,232,2]]]])
f = np.array([[[[[1,2,3],[23,232,2]]]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)

0
1
2
3
4
5


## 2 tareeqy hain dimesnion set krni ki . ya to uttni bracket laga do ya ndmin likh do 

# higer dimension

In [ ]:
g = np.array([1,3,4] , ndmin=6)
print(g)
print(g.ndim)

[[[[[[1 3 4]]]]]]
6


## indexing in numpyarray

In [20]:
m = np.array([1,2,3])
print("1st element" , m[0])
print("2nd element" , m[1])
print("Same as simple array/list")
d = [1,3,4,4]
print(d[0])

1st element 1
2nd element 2
Same as simple array/list
1


## indxing in more than 1 dimesnion

In [18]:
import numpy as np
z = np.array([[1,3,4],[3,4,5]])
print(z)
print("1st element on 2nd row is: ",z[1,0])
print("3rd element on 1st row is: ",z[0,2])
print("2rd element on 1st coloumn is: ",z[1,0])
print("4rth elemant on 2nd column is: ", z[1, 1])

[[1 3 4]
 [3 4 5]]
1st element on 2nd row is:  3
3rd element on 1st row is:  4
2rd element on 1st coloumn is:  3
4rth elemant on 2nd column is:  4


In [20]:
d = np.array([[[1,3,4],[2,3,4],[3,4,4]]])
n = np.array([[2,3],[3,3]])
print(d)
print(d.shape)
print(n)
print(n.shape)

[[[1 3 4]
  [2 3 4]
  [3 4 4]]]
(1, 3, 3)
[[2 3]
 [3 3]]
(2, 2)


In [43]:
j = np.array([[1,3,3]])
print(j)
print(j.shape)
print(j.ndim)

[[1 3 3]]
(1, 3)
2


In [47]:
k = np.array([1,3,4], ndmin = 3)
print(k)
print(k.ndim)
print(k.shape)

[[[1 3 4]]]
3
(1, 1, 3)


In [28]:
a = np.array([[3,9,1],[0,4,5] ,[2,7,8] ], ndmin = 3)
print(a)
print(a.shape)
print(a[0,2,2])

[[[3 9 1]
  [0 4 5]
  [2 7 8]]]
(1, 3, 3)
8


In [65]:
import numpy as np

a = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
])
print(a)
print(a.ndim , a.shape)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3 (2, 3, 3)


In [73]:
import numpy as np

b = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],

    [10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]
]])
print(b)
print(b.ndim , b.shape)
print(b[0,3,1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]]
3 (1, 6, 3)
11


In [75]:
c=  np.array([
        [[1,2,3],
        [4,5,6]],
        [[1,2,3],
        [3,3,3]]
    ])
print(c.shape)
print(c[1,1,2])

(2, 2, 3)
3


In [83]:
l = np.array([[[1,2,3]]], ndmin=5)
print(l.shape)
print(l[0,0,0,0,2])

(1, 1, 1, 1, 3)
3


## slicing in arrays

In [87]:
v = np.array([1,3,4,5,6,7,8,9])
print(v[1:4])
print(v[::2])

[3 4 5]
[1 4 6 8]


## 2d slicing

In [93]:
g = np.array([[1,2,3,5],[2,4,5,6]])
print(g[1,1:4])



[4 5 6]


## 3d slicing

In [97]:
hi = np.array([[[1,3,4],[5,6,4],[30,40,50]]])
print(hi[0,2,1:])

[40 50]


In [98]:
arshman = np.array([[1,2,3,4,5,6]] , ndmin=3)
print(arshman[0,0,2:])

[3 4 5 6]


In [101]:
haroon = np.array([[1,3,4,5],[20,23,23,43]] , ndmin =5)
print(haroon.shape)
print(haroon[0,0,0,1,1:])


(1, 1, 1, 2, 4)
[23 23 43]


In [104]:
d = np.array([1,3,4] , dtype='S')
print(d.dtype)
print(d)

|S1
[b'1' b'3' b'4']


In [106]:
arr = np.array([1,3,4])
print(arr.dtype)
arr2 = np.array([1,3,4],dtype = 'i4')
print(arr2.dtype)

int64
int32


In [108]:
arr = np.array([[1,3,4],[2,3,3],[2,3,3]])
print(arr.shape)

(3, 3)


In [ ]:
import numpy as np
arr1 = np.array([
    [1,3,4],
    [4,5,5]
])
arr2 = np.array([
    [3,5,5],
    [4,3,2]
])
print(np.concatenate((arr1,arr2), axis =1))  #concatactenate horizontally
print("----"*6)

arr1 = np.array([
    [1,3,4],
    [4,5,5]])
arr2 = np.array([
    [3,5,5],
    [4,3,2]
])
print(np.concatenate((arr1,arr2), axis =0))   # concatenate vetically

[[1 3 4 3 5 5]
 [4 5 5 4 3 2]]
------------------------
[[1 3 4]
 [4 5 5]
 [3 5 5]
 [4 3 2]]


### array spliting

In [124]:
FullArray = np.array([1,3,4,5])
print(np.array_split(FullArray,4))

[array([1]), array([3]), array([4]), array([5])]


In [130]:
arrat = np.array([1,4,4], ndmin =2)
print(arrat)
print(np.array_split(arrat,3))

[[1 4 4]]
[array([[1, 4, 4]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]


In [135]:
asha = np.array([1,3,4 ,4])
print(np.array_equal(asha,1))

False


## ravel and flatten fucntion ye multi dimesion arry ko single array mein convert kr deta hai

In [92]:
import numpy as np
array = np.array([[2,4,2,2],[1,3,4,4]])
print("dimension is: " , array.ndim)
d = array.flatten()
print("dimension is: ",d.ndim)
print(array.ndim)


dimension is:  2
dimension is:  1
2


In [91]:
c = np.array([1,3,4] , ndmin = 5)
print(c.ndim)
d = c.ravel()
print(d.ndim)
print(c.ndim)

5
1
5


In [ ]:
t = np.array([[[[[2,3,4]]]]])
print(t.ndim)
T = t.ravel()
print(T.ndim) ## converted it into 1 dimesion

5
1


## unique values

In [14]:
arra = np.array([1,2,3,2,3,4,5,5])
print(np.unique(arra))

[1 2 3 4 5]


In [18]:
arra = np.array([1,2,3,2,3,4,5,5])
print(np.unique(arra,return_index=True))

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 5, 6]))


In [19]:
arra = np.array([1,2,3,2,3,4,5,5])
print(np.unique(arra,return_index=True,return_counts=True))

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 5, 6]), array([1, 2, 2, 1, 2]))


## delete 

In [30]:
array = np.array([1,2,3,4])
new_array = np.delete(array,[3])
print(new_array)

[1 2 3]


In [32]:
my = np.array([
    [1,3,4],
    [1,4,5],
    [8,7,3]
])

x= np.delete(my , 2 ,axis=0)
print(x)

[[1 3 4]
 [1 4 5]]


In [33]:
my = np.array([
    [1,3,4],
    [1,4,5],
    [8,7,3]
])

x= np.delete(my , 2 ,axis=1)
print(x)

[[1 3]
 [1 4]
 [8 7]]


## maths 

### faida ye hai numpy mein pora data par 1 hi baar mein operation laga sakte hain agar simple list hoti to to humeni loop lagani partti

In [ ]:
list = [10,20,30]
for i in list:
    print(i+5 , end=" ")
print()    
for i in list:
    print(i*5,end=" ")
print()
for i in list:
    print(i**5,end=" ")
### ye slow ho jay big data ke liye iss liye numpy best hai yaar
   
    

15 25 35 
50 100 150 
100000 3200000 24300000 

In [ ]:
math = np.array([10,20,30])
print(math+5)
print(math*5)
print(math**5)

## loops ki zaroorat hi nahi hai

[15 25 35]
[ 50 100 150]
[  100000  3200000 24300000]


## agregaton fucntions

In [62]:
arr = np.array([2,3,4,5,8,9,32])
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))
print(np.max(arr))
print(np.min(arr))

9.0
5.0
93.71428571428571
9.680613912055666
32
2


In [ ]:
num = np.array([10,13,40,4,3,4,5,7,7,3])
print(num[::2]) #start:stop:step
print(num[::-1])

    

[10 40  3  5  7]
[ 3  7  7  5  4  3  4 40 13 10]
10 13 40 4 3 4 5 7 7 3 

## facning indexing

In [84]:
list = np.array([10,20,30,40,50,60])
print(list[[0,1,2]])


[10 20 30]


#### filtering /boolean masking use for filter the data without loops

In [ ]:
print(list[list>30])
print(list[list>40])
print(list[list>20]) 
## 

[40 50 60]
[50 60]
[30 40 50 60]


## reshsaping & manipulating

#### reshape tab hi ho sakata hai jab dim matching hon

#### numpy mein array fix hoti iss liye kush bhi add delete ya modification ke liye we have to make a new array

## Insert element

In [94]:
arr = np.array([1,3,4,5,6])
new_arr = np.insert(arr,1,2)
print(new_arr)

[1 2 3 4 5 6]


### insert in 2D

##### 2d ya multi dim mein hum koi element to add nahi karsakte bcz size matrix  ka fix hota hai.just koi row ya column ko remove ya add kar sakte hin easily

In [105]:
arr = np.array([[1,3],[1,4]]) 
new = np.insert(arr,2,[3,4],axis =0)
print(new)

[[1 3]
 [1 4]
 [3 4]]


In [109]:
an = np.array([[[1,2,3],[1,3,4],[1,3,3]]])
hi = np.insert(an,3,[3,3,3],axis=1)
print(hi)

[[[1 2 3]
  [1 3 4]
  [1 3 3]
  [3 3 3]]]


In [111]:
arr = np.array([[1,3],[1,4]]) 
new = np.insert(arr,2,[3,4],axis =None)
print(new)

[1 3 3 4 1 4]


In [112]:
z = np.append(arr,[5,6])
print(z)

[1 3 1 4 5 6]


In [113]:
arr1 = np.array(
    [1,2,3]
)
arr2 = np.array([4,5,6])
print(np.vstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]


In [114]:
arr1 = np.array(
    [1,2,3]
)
arr2 = np.array([4,5,6])
print(np.hstack((arr1,arr2)))

[1 2 3 4 5 6]


## broadcasting

In [117]:
h = np.array([[1,3,4,],[1,1,1]])
j = np.array([1,3,5])
print(j+h)

[[2 6 9]
 [2 4 6]]


## Handling Missing Values

In [124]:
arr = np.array([1,2,np.nan,4,np.nan,6])
missing_values = np.isnan(arr) # nan stand for not a number
print(missing_values)
cleaned = np.nan_to_num(arr, nan=4)
print(cleaned)

[False False  True False  True False]
[1. 2. 4. 4. 4. 6.]


## handle infinte numbers

In [2]:
import numpy as np
list =[1,3,4,4]
list = np.array([1,3,4,4])
print(list*2)

[2 6 8 8]


In [ ]:
list_p = [20,30,40,50]
diccount = 10
Final_prices = []
for i in prices:
    discount_prices = i - (i*10/100)
    Final_prices.append(discount_prices)

print(Final_prices)


[18.0, 27.0, 36.0, 45.0]


In [19]:
import numpy as np
prices = np.array([20,30,40,50])
discount=10
Final_prices = prices - (prices*10/100)
print(Final_prices)

[18. 27. 36. 45.]


In [ ]:
matrix = np.array([[1,2,3,4],
                 [1,4,4,4]])
vector = np.array([2,4,5,5])
final  = matrix + vector
print(final)

[[3 6 8 9]
 [3 8 9 9]]


In [23]:
final2 = np.dot(matrix,vector)
print(final2)

[45 58]


In [32]:
list = [1,3]
ls =  [2,3]
res = [i+j for i,j in zip(list,ls)]
print(res)
 

[3, 6]


In [25]:
list = np.array([1,3])
ls = np.array( [2,3])
print(list+ls)

[3 6]


## handle infinity

In [ ]:
arr = np.array([1,2,-np.inf,np.inf,5,6])  #-np.inf mean neagtive infinte values
print(arr)
print(np.isinf(arr))

[  1.   2. -inf  inf   5.   6.]
[False False  True  True False False]


In [ ]:
arr2 = np.array([1,3,4,np.nan,np.nan,5,6]) 
print(arr2)
print(np.isnan(arr2)) # nan mean not a number

[ 1.  3.  4. nan nan  5.  6.]
[False False False  True  True False False]


In [45]:
arr = np.array([np.inf,np.inf])
print(arr)
print(np.isinf(arr))

[inf inf]
[ True  True]


## Assign infinity values

In [49]:
arr = np.array([np.inf,np.inf])
clean_arr = np.nan_to_num(arr,neginf=-1000,posinf=1000)
print(clean_arr)

[1000. 1000.]


In [54]:
arr2 = np.array([1,3,4,np.nan,np.nan,5,6]) 
clean_arr2 = np.nan_to_num(arr2,nan=9)
print(clean_arr2)

[1. 3. 4. 9. 9. 5. 6.]
